apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: review-service-server
  name: review-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service-server
  template:
    metadata:
      labels:
        app: review-service-server
    spec:
      containers:
        - image: nrpndr/review-service:1.0
          name: review-service-server
          ports:
            - containerPort: 9014
              protocol: TCP
      restartPolicy: Always
