apiVersion: v1
kind: Service
metadata:
  labels:
    app: review-service-server
  name: review-service-server
spec:
  ports:
    - name: "9014"
      port: 9014
  selector:
    app: review-service-server
