apiVersion: v1
kind: Service
metadata:
  labels:
    app: review-service-mongodb
  name: review-service-mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: review-service-mongodb
