apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: review-service-mongodb
  name: review-service-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service-mongodb
  template:
    metadata:
      labels:
        app: review-service-mongodb
    spec:
      containers:
        - image: mongo:6.0.7
          name: review-service-mongodb
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
      restartPolicy: Always